export const RouteList = {
  Home: {
    CarDemo1: `/`,
    CarDemo2: `/car-2`,
    JobDemo1: `/job`,
    JobDemo2: `/job-2`,
    JobDemo3: `/job-3`,
    PropertyDemo1: `/property`,
    PropertyDemo2: `/property-2`,
  },

  Property: {
    Grid: {
      Property2Grid: `/property/grid/property-2-grid`,
      Property2RightGrid: `/property/grid/property-2-right-grid`,
      Property3Grid: `/property/grid/property-3-grid`,
      Property3RightGrid: `/property/grid/property-3-right-grid`,
      Property4Grid: `/property/grid/property-4-grid`,
      PropertyGridNoSidebar: `/property/grid/property-grid-no-sidebar`,
    },
    Listing: {
      PropertyLeftList: `/property/listing/property-left-list`,
      PropertyRightList: `/property/listing/property-right-list`,
      PropertyVideoList: `/property/listing/property-video-list`,
      PropertyThumbList: `/property/listing/property-thumb-list`,
      PropertyWithoutSlider: `/property/listing/property-without-slider`,
    },
    Other: {
      PropertyLeftDrawer: `/property/other/property-left-drawer`,
      PropertyRightDrawer: `/property/other/property-right-drawer`,
      PropertyInfiniteScroll: `/property/other/property-infinite-scroll`,
      PropertyLoadMore: `/property/other/property-load-more`,
      PropertyParallax: `/property/other/property-parallax`,
      PropertyGridWithoutSlider: `/property/other/property-grid-without-slider`,
    },
    Map: {
      MapLeft: `map-left`,
      MapRight: `map-right`,
      MapList: `map-list`,
      MapModal: `map-modal`,
    },
    Detail: {
      PropertyClassic: `property-classic`,
      PropertyScrollspy: `property-scrollspy`,
      PropertyTab: `property-tab`,
      PropertyAccordion: `property-accordion`,
      PropertyImageSlider: `property-image-slider`,
      PropertySticky: `property-sticky`,
      PropertySidebarLayout: `property-sidebar-layout`,
      PropertyVideo: `property-video`,
      PropertyThumbSlider: `property-thumb-slider`,
      PropertyAnimatedIcon: `property-animated-icon`,
    },
    PropertyWishlist: `property-wishlist`,
  },

  Car: {
    Grid: {
      Car2Grid: `car-2-grid`,
      Car2RightGrid: `car-2-right-grid`,
      Car3Grid: `car-3-grid`,
      Car3RightGrid: `car-3-right-grid`,
      CarNoSidebar: `car-no-sidebar`,
    },
    Listing: {
      CarLeftList: `car-left-list`,
      CarRightList: `car-right-list`,
    },
    Other: {
      CarLeftDrawer: `car-left-drawer`,
      CarRightDrawer: `car-right-drawer`,
      CarInfiniteScroll: `car-infinite-scroll`,
      CarLoadMore: `car-load-more`,
      CarTopCategory: `car-top-category`,
      CarTopFilter: `car-top-filter`,
      CarWithoutSlider: `car-without-slider`,
    },
    Detail: {
      CarClassic: `car-classic`,
      CarLayout1: `car-layout-1`,
      CarLayout2: `car-layout-2`,
      CarSlider: `car-slider`,
      CarExpandSlider: `car-expand-slider`,
      CarModernSlider: `car-modern-slider`,
      CarScrollspy: `car-scrollspy`,
      CarVideo: `car-video`,
      CarClassicSlider: `car-classic-slider`,
      CarThumbnailSlider: `car-thumbnail-slider`,
    },
    CarWishlist: `car-wishlist`,
  },

  Job: {
    Grid: {
      JobGridProgress: `job-grid-progress`,
      JobGridType2: `job-grid-type-2`,
      JobGridType3: `job-grid-type-3`,
      JobLeftSidebar: `job-left-sidebar`,
      JobRightSidebar: `job-right-sidebar`,
      JobGridNoSidebar: `job-grid-no-sidebar`,
    },
    Listing: {
      JobLeftList: `job-left-list`,
      JobRightList: `job-right-list`,
      JobListNoSidebar: `job-list-no-sidebar`,
    },
    Other: {
      jobLeftDrawer: `job-left-drawer`,
      jobRightDrawer: `job-right-drawer`,
      jobInfiniteScroll: `job-infinite-scroll`,
      jobLoadMore: `job-load-more`,
      jobAd: `job-ad`,
      jobFilter: `job-filter`,
      jobFullList: `job-full-list`,
      jobBothSidebar: `job-both-sidebar`,
      jobListStyle2: `job-list-style-2`,
    },
    Detail: {
      JobDetail1: `job-detail-1`,
      JobDetail2: `job-detail-2`,
      JobDetail3: `job-detail-3`,
      JobDetail4: `job-detail-4`,
      JobDetail5: `job-detail-5`,
    },
    JobWishlist: `job-wishlist`,
  },

  Pages: {
    Blog: {
      BlogLeftSidebar: `blog-left-sidebar`,
      BlogRightSidebar: `blog-right-sidebar`,
      Blog2Grid: `blog-2-grid`,
      Blog2GridRight: `blog-2-grid-right`,
      BlogTitle: `blog-title`,
      BlogLayout1: `blog-layout-1`,
      BlogNoSidebar: `blog-no-sidebar`,
      BlogToSlider: `blog-to-slider`,
      Blog3Masonry: `blog-3-masonry`,
      BlogLoadMore: `blog-load-more`,
      BlogLeftList: `blog-left-list`,
      BlogRightList: `blog-right-list`,
      BlogInfiniteScroll: `blog-infinite-scroll`,
      Detail: {
        BlogLeftClassic: `blog-left-classic`,
        BlogRightClassic: `blog-right-classic`,
        BlogVideoLayout: `blog-video-layout`,
        BlogAudioLayout: `blog-audio-layout`,
        BlogSliderLayout: `blog-slider-layout`,
        BlogQuoteLayout: `blog-Quote-layout`,
      },
    },
    Portfolio: {
      Portfolio2Grid: `portfolio-2-grid`,
      Portfolio3Grid: `portfolio-3-grid`,
      Portfolio4Grid: `portfolio-4-grid`,
      PortfolioTransform: `portfolio-transform`,
      PortfolioVideoModal: `portfolio-video-modal`,
      PortfolioGalleryIcon: `portfolio-Gallery-icon`,
      PortfolioImageChange: `portfolio-image-change`,
      PortfolioBoxSlider: `portfolio-box-slider`,
      PortfolioParallax: `portfolio-parallax`,
      PortfolioVerticalSlider: `portfolio-vertical-slider`,
      PortfolioCreativeFull: `portfolio-Creative-full`,
      PortfolioModern: `portfolio-modern`,
      Detail: {
        PortfolioDetail1: `portfolio-detail-1`,
        PortfolioDetail2: `portfolio-detail-2`,
      },
    },
    Other: {
      AboutUs1: `about-1`,
      AboutUs2: `about-2`,
      AboutUs3: `about-3`,
      ContactUs1: `contact-1`,
      ContactUs2: `contact-2`,
      ContactUs3: `contact-3`,
      Services: `services`,
      Team: `team`,
      Pricing: `pricing`,
      Testimonial: `testimonial`,
      Faq: `faq`,
      UserDashboard: `user-dashboard`,
      Privacy: `privacy`,
      Condition: `condition`,
      Error404: `404`,
      Login1: `login-1`,
      Login2: `login-2`,
      Login3: `login-3`,
      Login4: `login-4`,
      SignUp1: `signup-1`,
      SignUp2: `signup-2`,
      SignUp3: `signup-3`,
    },
  },
};
